export default {
		color_0:'black',
		color_1:'red',
		color_2:'green',
		buttons: [],
		menu_selected: null,
		trame_type:null,
		line : null,
		isDown: null,
		rect: null,
		PORT_SIZE: null,
		selected: null,
		tab_workstation: null,
		tab_cable: null,
		last_object: null,
		last_object_port_nb: null,
		line_creation: null,
		tab_images: null,
		current: null,
		buttons_selected: null,
		start:null,
		nb_workstation:null,
		y: null,
		WorkStationType: null,
		text:'oui'
}